### ISSUE TITLE
cch editor shows nothing

### ISSUE THREAD

**Issue by ghost** [maykar/compact-custom-header#141]
## Describe the bug:

The opened CCH Editor shows nothing. (screenshot below)

## Config YAML:
```yaml
<!-- Paste your lovelace code for the card after this line -->
cch:
  notifications: overflow
  swipe: true
  swipe_animate: flip
  voice: hide
```
## HA and/or Browser Error:

`2019-06-28 16:35:43 ERROR (MainThread) [frontend.js.latest.201906260] http://192.168.2.150:8123/community_plugin/compact-custom-header/compact-custom-header.js:423:26 TypeError: null is not an object (evaluating 'paperIconButton.hasAttribute')`

## HA, Card, and Browser Versions:

version: since 1.1.2
home assistant version: 0.95.1
browser version: ios app (version: 1.5.1)
Storage Mode

This is the opened editor:

![DC6243C0-A279-43A5-AAE6-002F72554FFE](https://user-images.githubusercontent.com/52260298/60350641-444c4680-99c4-11e9-8fda-494e7e337856.jpeg)

**Comment by helenclarko** [comment]
Chrome Console Error:
```
Uncaught (in promise) TypeError: Cannot read property 'style' of null
    at styleButtons (compact-custom-header.js:414)
    at run (compact-custom-header.js:105)
    at compact-custom-header.js:90
```

**Comment by maykar** [comment]
@helenclarko is this related to the same issue? do you get the same error in your logs as @fabian1185?

**Comment by tube0013** [comment]
I just installed and get this as well. I don't see an error in my chrome console.

**Comment by helenclarko** [comment]
Sorry Maykar, 
Same issue different error, I'll remove my comment.

**Comment by maykar** [comment]
@tube0013 Do you get the same error as @fabian1185 in your HA logs? Are you on iOS?

**Comment by tube0013** [comment]
@maykar no error in my HA logs.

**Comment by maykar** [comment]
Tracked this one down to the "overflow" feature and it should be fixed in in the next release. Thank you.

**Comment by chenchen119** [comment]
I just updated to the latest release 1.1.7 and the editor still shows blank (was on 1.1.4 having the issue).
Still see this error on the console:

```
compact-custom-header.js:415 Uncaught (in promise) TypeError: Cannot read property 'style' of null
    at styleButtons (compact-custom-header.js:415)
    at run (compact-custom-header.js:104)
    at compact-custom-header.js:89
```

**Comment by maykar** [comment]
@chenchen119 When does this happen? If you refresh the Lovelace page, does it happen immediately, does it happen when you go into "configure ui", when you come out of "configure ui"?

If you do a full refresh of the lovelace page and immediately go into "configure ui" and then "CCH settings" do the settings display?

**Comment by chenchen119** [comment]
@maykar 
Happens every time I click "CCH Settings" -> goes to blank bar, shows message on chrome console
It happens everytime, so I cannot get into the settings at all.

![image](https://user-images.githubusercontent.com/4780124/60377287-474a3580-99ca-11e9-841d-7cf64218e288.png)

**Comment by ghost** [comment]
> Tracked this one down to the "overflow" feature and it should be fixed in in the next release. Thank you.

@maykar 
Here is all ok now (version 1.1.7):

![F2F727D6-8AA4-4581-971C-350049E19D3A](https://user-images.githubusercontent.com/52260298/60379637-ab0a4800-9a36-11e9-9b8a-2a9299cabe3f.png)

**Comment by mmatesic01** [comment]
Updated to 1.1.7 and it is still the same problem.

**Comment by maykar** [comment]
@mmatesic01 Yes, this is still an issue. It seems there are multiple things preventing the editor from showing at the moment. One has been fixed, tracking down the rest. Please, share the error's you might have from your logs and browser dev tools.

**Comment by IIIdefconIII** [comment]
Got the same, i tough i was messing up, glad i found this issue on github.
No errors related to this component in log.

Waiting for FIX.
Tried basic stuff like other browser, clearing cache, update ha to latest version.

![image](https://user-images.githubusercontent.com/9917659/60382362-61375700-9a62-11e9-93ed-db073c9f056d.png)

**Comment by maykar** [comment]
Those having issues, please update to 1.1.8 and let me know if it works for you.

**Comment by mmatesic01** [comment]
it's the same for me after updating to 1.1.8



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by circa1665** [comment]
Still the same for me on 1.1.8

**Comment by maykar** [comment]
@mmatesic01  @circa1665  Please provide more info. 

* What browser/s are you using?
* Have you done a hard refresh of the page (Ctrl+Shift+R) or cleared your cache?
* Do any errors display in the HA logs or in your browsers dev tools console (F12)?
* After adding cch config manually, does the editor then work?
* What does your config/resources section look like?

**Comment by IIIdefconIII** [comment]
@maykar for me its working since i upgraded from 1.1.7 to 1.1.8, reloaded cache and all good, thanks

**Comment by mmatesic01** [comment]
cleared cache 
I use latest opera (android and windows) and chrome

my existing setup in lovelace
```
cch:
  swipe: true
  swipe_animate: flip
  voice: hide
```

F12
error in chrome 
```
compact-custom-header.js:417 Uncaught (in promise) TypeError: Cannot read property 'style' of null
    at styleButtons (compact-custom-header.js:417)
    at run (compact-custom-header.js:104)
    at compact-custom-header.js:89
styleButtons @ compact-custom-header.js:417
run @ compact-custom-header.js:104
(anonymous) @ compact-custom-header.js:89
Promise.then (async)
showEditor @ compact-custom-header.js?track=true:931
(anonymous) @ compact-custom-header.js?track=true:271
```

**Comment by IIIdefconIII** [comment]
@

> cleared cache
> I use latest opera (android and windows) and chrome
> 
> my existing setup in lovelace
> cch:
> swipe: true
> swipe_animate: flip
> voice: hide
> 
> F12
> error in chrome
> compact-custom-header.js:417 Uncaught (in promise) TypeError: Cannot read property 'style' of null
> at styleButtons (compact-custom-header.js:417)
> at run (compact-custom-header.js:104)
> at compact-custom-header.js:89
> styleButtons @ compact-custom-header.js:417
> run @ compact-custom-header.js:104
> (anonymous) @ compact-custom-header.js:89
> Promise.then (async)
> showEditor @ compact-custom-header.js?track=true:931
> (anonymous) @ compact-custom-header.js?track=true:271

try without the cch:, im not using that and it working fine

**Comment by mmatesic01** [comment]
deleted cch: and everything connected to it,saved, sw restarted hassio, still the same.

**Comment by circa1665** [comment]
Cleared cache again and now this working for me :)

**Comment by mmatesic01** [comment]
cleared cache on opera and chorme, no luck. still the same

**Comment by Djebouh** [comment]
upgrade to 1.1.8, cleared  cache  on chrome, it  works  well, thanks !

**Comment by mmatesic01** [comment]
"at styleButtons (VM44 compact-custom-header.js:417)" points to "buttons[button].style.cssText = `"
"at run (VM44 compact-custom-header.js:104)" points to "styleButtons(buttons, tabs);"
"at VM44 compact-custom-header.js:89" points to "run();"

**Comment by mmatesic01** [comment]
1.1.9 works. thanks

**Comment by papperone** [comment]
I've same problem despite all actions taken:
- it started when the new CCH option was deployed
- I upgraded up to 1.1.8 (cannot see 1.1.9 on hassio custom configurator)
- used lots of  different browsers (Chrome, FF, Opera, Explorer, Edge) and all behave the same
- cleaned up cache/history/cookies an all browser without any change
please let me know which futher debug info you may need else this component is pretty much unmanageable

**Comment by maykar** [comment]
@papperone You have two options, upgrade to 1.1.9 or downgrade to 1.0.4b9.  If you need to you can install both versions manually.

**Comment by maykar** [comment]
Closing this one as 1.1.9 appears to have solved the remaining issues. Feel free to make a new issue if anyone is still having problems. Big thank you to @chenchen119 and @cdrom1028 for their help in troubleshooting these issues.

**Comment by papperone** [comment]
Installed 1.1.9 and this is not solved at all, but behaviour changed, now I get a "Loading spinning circle" which rotates forever but still no configuration windows appears.
No point to revert to 1.0.4b9 as it is with old setup of putting the reference to each view and I already updated by YAML files...
Why you supposed 1.1.9 fix this bug as it's not? Can I provide you more details to understand why on my hassio it's still not working?

**Comment by maykar** [comment]
The original error for which this issue was made was solved in 1.1.7 as the original poster has stated: https://github.com/maykar/compact-custom-header/issues/141#issuecomment-506925243

If you are still having issues submit a new issue with the required information.
