### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by Tontze** [maykar/compact-custom-header#47]
**Describe the bug**

After updating no longer works. Did what was told in readme. 

**Config**
```
  - id: 50
    title: Test Page
    background: center / cover no-repeat url("/local/background-abstract.jpg") fixed
    cards:
      - type: custom:compact-custom-header
        main_config: true
        menu: overflow
        options: clock
        voice: hide
        clock_format: 24
```
```
  - url: /local/custom-lovelace/compact-custom-header/compact-custom-header.js?v=1.0.0b1
    type: module
```

**Error**

in homeassistant.log 

``` 
:8123/lovelace/5:0:0 Uncaught SyntaxError: The requested module './compact-custom-header.js' does not provide an export named 'html'

```

**Version**
0.87.1 Home Assistant Version
1.0.0b1 Compact Custom Header Version
Google chrome Browser type and version

**Comment by maykar** [comment]
Try clearing your cache & make sure you've copied from raw files on github

**Comment by Tontze** [comment]
done both allready

**Comment by maykar** [comment]
Please, try out the newest version of the card and let me know if it solves your issue.

**Comment by maykar** [comment]
If issue persists, are there any errors for CCH in your browsers dev tools (F12)?

**Comment by maykar** [comment]
Also, was your update done with custom-updater?

**Comment by maykar** [comment]
Addressed this further with the latest release 1.0.0b3

**Comment by Tontze** [comment]
Nope, aint working :/
```
:8123/lovelace/0:0:0 Uncaught SyntaxError: The requested module './compact-custom-header.js' does not provide an export named 'html'
```

**Comment by maykar** [comment]
Sounds like a caching issue as html is no longer imported in the new versions.

**Comment by maykar** [comment]
I would delete the card and reinstall, make sure the version number is increased in resources
